//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.UserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChampionsJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChampionsJson() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserInterface.UserInterface.Resources.ChampionsJson", typeof(ChampionsJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {&quot;data&quot;:{&quot;Jax&quot;:{&quot;id&quot;:24,&quot;key&quot;:&quot;Jax&quot;,&quot;name&quot;:&quot;Jax&quot;,&quot;title&quot;:&quot;Grandmaster at Arms&quot;,&quot;image&quot;:{&quot;full&quot;:&quot;Jax.png&quot;,&quot;sprite&quot;:&quot;champion1.png&quot;,&quot;group&quot;:&quot;champion&quot;,&quot;x&quot;:144,&quot;y&quot;:48,&quot;w&quot;:48,&quot;h&quot;:48},&quot;skins&quot;:[{&quot;id&quot;:24000,&quot;name&quot;:&quot;default&quot;,&quot;num&quot;:0},{&quot;id&quot;:24001,&quot;name&quot;:&quot;The Mighty Jax&quot;,&quot;num&quot;:1},{&quot;id&quot;:24002,&quot;name&quot;:&quot;Vandal Jax&quot;,&quot;num&quot;:2},{&quot;id&quot;:24003,&quot;name&quot;:&quot;Angler Jax&quot;,&quot;num&quot;:3},{&quot;id&quot;:24004,&quot;name&quot;:&quot;PAX Jax&quot;,&quot;num&quot;:4},{&quot;id&quot;:24005,&quot;name&quot;:&quot;Jaximus&quot;,&quot;num&quot;:5},{&quot;id&quot;:24006,&quot;name&quot;:&quot;Temple Jax&quot;,&quot;num&quot;:6},{&quot;id&quot;:24007,&quot;name&quot;:&quot;Nemesis Jax&quot....
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
    }
}
